version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pokegpt-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - pokegpt-network

  frontend:
    build: ./frontend
    container_name: pokegpt-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - pokegpt-network

networks:
  pokegpt-network:
    driver: bridge 