version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pokegpt-backend
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CORS_ORIGINS=https://poke-gpt.jvthunder.org
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pokegpt-frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend

networks:
  pokegpt-network:
    driver: bridge
